config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :friends do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :friend
end

app/models/friend.rb
class Friend < ApplicationRecord
    has_many :comment, dependent: :destroy
    validates :name, presence: true, length: {minimum: 2}
    validates :age, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    def create 
        @friend=Friend.find(params[:friend_id])
        @comment=@friend.comment.create(params.require(:comment).permit(:commenter, :body))
        redirect_to friend_path(@friend)
    end
    
    def destroy
        @friend=Friend.find(params[:friend_id])
        @comment=Comment.find(params[:id])
        @comment.destroy
        redirect_to friend_path(@friend)
    end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    before_action :authenticate_user!
    def index
        @all = Friend.all
    end

    def new
        @new ="form"
        @friend = Friend.new()
    end

    def create
        @friend = Friend.new(params.require(:friends).permit(:name,:age))
        if @friend.save
            redirect_to @friend
        else
            render 'new'
        end
    end

    def show
        @friend = Friend.find(params[:id])
    end

    def edit
        @friend = Friend.find(params[:id])
    end

    def update
        @friend = Friend.find(params[:id])
        if @friend.update(params.require(:friend).permit(:name,:age))
            redirect_to @friend
        else
            render 'edit'
        end
    end

    
    def destroy
        @friend = Friend.find(params[:id])
        @friend.destroy
    
        redirect_to friends_path
    end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @name = current_user.email
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friends/_form.html.erb
<%= form_with model: @friend, local: true do |form| %>

  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@friend.errors.count, "error") %> prohibited
        this friend from being saved:
      </h2>
      <ul>
        <% @friend.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/friends/edit.html.erb
<h2>Edit friend</h2>

<%= render 'form'%>

<%= link_to 'Back', friends_path%>

app/views/friends/index.html.erb
<% @all.each do |one| %>
    <p>--------------------------------------------------</p>
      <p>Name: <%= one.name %></p>
      <p>Age: <%= one.age %></p>
      <p><%= link_to 'Show', friend_path(one) %></p>
      <p><%= link_to 'Edit', edit_friend_path(one) %></p>
      <p><%= link_to 'Delete', friend_path(one),
        method: :delete,
      data: { confirm: 'Enta mot2aked yasta?'} %></p>
    <p>--------------------------------------------------</p>
  <% end %>
  <%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<%= @new %>

<%= form_with scope: :friends, url: friends_path, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :age %><br>
    <%= form.number_field :age %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/friends/show.html.erb
<p>Name : <%= @friend.name %></p>
<p>Age : <%= @friend.age %></p>

<h2>Reviews: </h2>

<% @friend.comment.each do |comment|%>
<p>
    <strong><%= comment.commenter%></strong>: <%= comment.body %>
</p>
<p>
    <%= link_to 'Delete Comment', [comment.friend, comment], 
        method: "delete",
        data: {confirm: 'Sure yasta?'}%>
</p>
<%end%>

<h2>Add a comment:</h2>
<%= form_with(model: [ @friend, @friend.comment.build ], local: true) do |form| %>
<p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
</p>
<p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
</p>
<p>
    <%= form.submit %>
</p>
<% end %>
<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Lab2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% if user_signed_in? %>
    <%= link_to 'Home', welcome_index_path%>
    <%= link_to 'Friends', friends_path%>
    <%end%>
     <% if !user_signed_in? %>
     <%= link_to 'Login' , new_user_session_path %>
     <%= link_to 'Sign up' , new_user_registration_path %>
    <%end%>
    <%= yield %>
    <% if user_signed_in? %>

      <%= link_to'Logout', destroy_user_session_path, method: :delete%>

    <%end%>
</body>

</html>

app/views/welcome/index.html.erb
<h1>Welcome <%= @name %></h1>
<%= link_to 'My Friends', controller: 'friends' %>